# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'sunduskXingyun' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sunduskXingyun
pod 'AMap3DMap', '~> 4.1.0'  #3D地图SDK
#pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使⽤)
pod 'AMapSearch' #搜索服务SDK
end
